<?php
/*
 * container-fluid - określa responsywny, główny kontener
 * row - wiersz (kolumna pozioma)
 * col-(xs/sm/md/lg)-# - kolumna (#-szerokość-max.12) z dopiskiem np. col-xs-offset-X ustawiamy przesunięcie w prawo
 * 
 */
?>



<div class="row">
    <div class="main-title">
        <div class="col-xs-12">
            <h1>mynote<small> osobisty notes online <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span></small></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="jumbotron">
            Wygląda na to, że żeby skorzystać z tego caceńka, będziesz musiał się zalogować ;)
        </div>
    </div>

</div>




