<?php
/*
 * container-fluid - określa responsywny, główny kontener
 * row - wiersz (kolumna pozioma)
 * col-(xs/sm/md/lg)-# - kolumna (#-szerokość-max.12) z dopiskiem np. col-xs-offset-X ustawiamy przesunięcie w prawo
 * 
 */
?>
<div class="row">
    <div class="col-xs-12 main-title">
        <h1>myNote<small> Osobisty notes online <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span></small></h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="jumbotron">
            <p class="lead">Wygląda na to, że żeby skorzystać z tego cacka, będziesz musiał się zalogować.</p>
        </div>
    </div>
</div>




