<?php if ($this->totalItemCount!=0) : ?>
<nav>
  <ul class="pagination">
<?php

$kolor = $this->getColor($this->color,1); // przekazany w paginationControl kolor sekcji
///var_dump($kolor);

if ($this->pageCount == 1) {
    return;
}
if (isset($this->previous)) {
    echo '<li><a href="' . $this->url(array('page' => $this->first)) . '" style="color: '.$kolor.' !important;"> « </a></li> '; // $this->previous
} else {
    // nie wyświetlaj mi niczego
}
foreach ($this->pagesInRange as $page) {
    if ($page != $this->current) {
        echo ' <li><a href="' . $this->url(array('page' => $page)) . '" style="color: '.$kolor.' !important;">' . $page . '</a></li> ';
    } else {
        echo '<li class="active"><a style="background-color : '.$kolor.' !important; 
                                           border : 1px solid '.$kolor.' !important;
                                            
                ">', $page , '</a></li> ';
    }
}
if (isset($this->next)) {
    echo '<li><a href="' . $this->url(array('page' => $this->last)) . '" style="color: '.$kolor.' !important;"> » </a></li>'; // $this->next
} else {
    // nie wyświetlaj mi niczego
}
?>
  </ul>
</nav>
<?php endif; 
?>