<?php // var_dump($this->getVars())       ?>
<div id="view-content">
    
    <div class="btn-group" role="group">
        
        <button type="button" class="btn btn-success btn-lg" onclick="<?= $this->redirecter(array(),'note_section_index') ?>"><span class="glyphicon glyphicon-share-alt fa-rotate-180" aria-hidden="true"></span></button>
        
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-success dropdown-toggle btn-lg" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-wrench">&nbsp;</i><span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><a href="<?= $this->url(array('section_id'=>$this->section->id), 'note_section_edit'); ?>"><i class="fa fa-pencil"></i> Edytuj sekcję</a></li>
            </ul>
        </div>
        
        <button onclick="<?= $this->redirecter(array('section_id'=>$this->section->id), 'note_note_add'); ?>" class="btn btn-success btn-lg" type="button" ><i class="fa fa-plus fa-lg"></i></button>
        
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h2>
                Sekcja <small><?php echo $this->section->fullname; ?></small>
            </h2>
        </div>
    </div>
    <div class="space"></div>

    
    <div class="row">
        <div class="col-xs-12">
            <?php if ($this->notes != NULL) { ?>
            
                <?= ($this->paginator) ? $this->paginationControl($this->paginator, 'Sliding', 'pagination_note.phtml', array('color' => $this->section->color)) : ''; ?>
                
                <div class="table-responsive">
                    <table class="table table-striped-columns index-note">
                        <thead>
                        <tr style="background-color: <?= $this->getColor($this->section->color, Application_Model_DbTable_Note::INDEX_TABLE_HEADER_BG) ?>; ">
                            <th class="text-center" style="width: 20%; color: <?= $this->getColor($this->section->color, Application_Model_DbTable_Note::INDEX_TABLE_HEADER_TXT) ?>;">Tytuł</th>
                            <th class="text-center" style="width: 50%;color: <?= $this->getColor($this->section->color, Application_Model_DbTable_Note::INDEX_TABLE_HEADER_TXT) ?>;">Treść</th>
                            <th class="text-center" style="width: 20%;color: <?= $this->getColor($this->section->color, Application_Model_DbTable_Note::INDEX_TABLE_HEADER_TXT) ?>;">Utworzono / edytowano DODAJ!!!</th>
                            <th class="text-center" style="width: 10%;color: <?= $this->getColor($this->section->color, Application_Model_DbTable_Note::INDEX_TABLE_HEADER_TXT) ?>;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->paginator as $oRow): ?>
                            <?= $this->partial('note/note.phtml', array('row' => $oRow, 'color'=>$this->section->color)) ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table> 
                </div>
            
            <?php } // if 
            else {
            ?>
                Brak wpisów w tej sekcji.
            <?php } // else  ?>
        </div>
    </div>


</div>


