<?php // var_dump($this->getVars())       ?>
<div id="view-content">
    
    <div class="btn-group" role="group">
        
        <button type="button" class="btn btn-success btn-lg" onclick="<?= $this->redirecter(array(),'note_section_index') ?>"><span class="glyphicon glyphicon-share-alt fa-rotate-180" aria-hidden="true"></span></button>
        
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-success dropdown-toggle btn-lg" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-wrench">&nbsp;</i><span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><a href="<?= $this->url(array('section_id'=>$this->section->id), 'note_section_edit'); ?>"><i class="fa fa-pencil"></i> Edytuj sekcję</a></li>
            </ul>
        </div>
        
        <button onclick="<?= $this->redirecter(array('section_id'=>$this->section->id), 'note_note_add'); ?>" class="btn btn-success btn-lg" type="button" ><i class="fa fa-plus fa-lg"></i></button>
        
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h2>
                Notatki <small><span class="label label-<?= $this->section->color ?>"><?php echo $this->section->fullname; ?></span></small>
            </h2>
             
        </div>
    </div>
    <div class="space"></div>

    
    <div class="row">
        <div class="col-xs-12">
            <?php if ( !empty($this->notes) ) { ?>
                
                <div class="table-responsive">
                    
                    <table id="table-notes" class="table" cellspacing="0" width="100%">
                        <thead>
                            <tr style="background-color: <?= $this->getColor($this->section->color, Application_Model_DbTable_Note::INDEX_TABLE_HEADER_BG) ?>; ">
                                <th>Tytuł</th>
                                <th class="hidden-xs">Treść</th>
                                <th class="hidden-sm hidden-xs">Data utworzenia / ost. edycji</th>
                                <th>Operacje</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->notes as $oRow): ?>
                            <tr>
                                <td class="linkable" href='<?= $this->url(array('note_id' => $oRow->id), 'note_note_show'); ?>'><?= $oRow->title ?></td>
                                <td class="linkable hidden-xs" href='<?= $this->url(array('note_id' => $oRow->id), 'note_note_show'); ?>'><?= substr(strip_tags($oRow->content), 0, 45) ?>...</td>
                                <td class="linkable hidden-sm hidden-xs" href='<?= $this->url(array('note_id' => $oRow->id), 'note_note_show'); ?>'><?= $oRow->creationDatetime ?></td>
                                <td style="text-align: center;">
                                    
                                    <a title="Pokaż" href="<?= $this->url(array('note_id' => $oRow->id), 'note_note_show'); ?>" ><button type="button" class="btn btn-primary"><i class="fa fa-eye" aria-hidden='true'></i></button></a>
                                    <a title="Edycja" href="<?= $this->url(array('note_id' => $oRow->id), 'note_note_edit'); ?>" ><button type="button" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden='true'></i></button></a>
                                    <a title="Czy na pewno chcesz usunąć notatkę?" href="<?= $this->url(array('note_id' => $oRow->id), 'note_note_delete'); ?>" type="delete-action"><button type="button" class="btn btn-primary"><i class="fa fa-trash" aria-hidden='true'></i></button></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table> 
                </div>
            
            <?php } // if 
            else {
            ?>
                Brak wpisów w tej sekcji.
            <?php } // else  ?>
        </div>
    </div>


</div>
<script type='text/javascript'>
$(document).ready(function() {
    $('#table-notes').DataTable( {
        // sorting by 3-rd column
        "order": [[ 3, "desc" ]]
    } );
    
    // It allows every row of data to redirect to details
    $('#table-notes').on( 'click', 'tbody tr td.linkable', function () {
        window.location.href = $(this).attr('href');
    } );
} );
</script>