<h1>
    Błąd <?= $this->errorCode ?>
</h1>
<h3>
    <?= $this->message ?>
</h3>

<?php if (isset($this->exception)): ?>
    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>
    <?php

 endif;
