<?php  
// autouzupełnianie
if($this->sections) {
    foreach($this->sections as $section) {
        $zmienna[] = $section->fullname;
    }
    print "<script type=\"text/javascript\">";
    print "var zmienna=new Array()\n";
    foreach($zmienna as $tym) print "zmienna.push('$tym')\n";
    // w "zmienna" mam WSZYSTKIE Sekcje

    //print "alert(zmienna)";
    print "</script>";
?>  
<script type="text/javascript">
  $(function() {
//    var availableTags = [
//      "ActionScript",
//      "AppleScript",
//      ....
//    ];
    $( "#search-box" ).autocomplete({
      delay: 500,
      source: zmienna, // dane
      classes: {
        "ui-autocomplete": "klasa"
      },
    });

  });
</script>
<?php } ?>

    <div id="row">
    <div class="col-xs-12">
    
    <!-- Przyciski akcji -->
    <div class="row">
        <div class="col-xs-12">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-success btn-lg" title="Dodaj sekcję..." onclick="<?= $this->redirecter(array(), 'note_section_add') ?>">
                    <i class="fa fa-plus fa-lg"></i>
                </button>
                <?php if($this->sections): ?>
                <button id="edit" class="btn btn-success btn-lg" type="button" title="Włącz tryb edytowania sekcji..."><i class="fa fa-wrench fa-lg"></i></button>
                <?php endif; ?>
            </div>

        </div>
    </div>
    <!-- /przyciski akcji -->
    
    <div class="space"></div>
    
    <div class="row">
        <div class="col-xs-12">
            <h4><?php  if($this->sections): ?>
                <h2>Sekcje</h2>
                <?php else: ?>
                Brak sekcji<br /><br /><small>Nie masz jeszcze sekcji. Aby utworzyć, kliknij "+" powyżej.</small>
                <?php endif; ?>
            </h4>
        </div>
    </div>
    
    <div class="space"></div>

    <!-- Wyszukiwarka sekcji -->
    <?php if($this->sections): ?>
    <div class="row">
        <div class="col-xs-12">
            <?= $this->form ?>
        </div>
    </div>
    <?php endif; ?>
    <!-- /wyszukiwarka sekcji -->
    
    <div class="space"></div>
    
    <!-- Paginacja góra -->
    <div class="row">
        <div class="col-sm-6 col-xs-12">
            <?= ($this->paginator) ? $this->paginationControl($this->paginator, 'Sliding', 'pagination_section1.phtml', array()) : '' ?>
        </div>
    </div>
    <!-- /paginacja góra -->

    <!-- Lista sekcji -->
    <ul id="sortable">
    <?php foreach ($this->paginator as $oRow): ?>
        <?= $this->partial('section/section.phtml', array('row' => $oRow)) ?>
    <?php endforeach; ?>
    </ul>
    <!-- /lista sekcji -->

    <!-- Paginacja dół -->
    <div class="row">
        <div class="col-sm-6 col-xs-12">
            <?= ($this->paginator) ? $this->paginationControl($this->paginator, 'Sliding', 'pagination_section1.phtml', array()) : '' ?>
        </div>
    </div>
    <!-- /paginacja dół -->
    </div>
    </div>

<script>
$(document).ready(function () {
    $('[name=edit-button]').hide();
    $('[name=delete-button]').hide();
    $('[type=search]').hide();
});

$('#search-button').mouseenter(function () {
    $('[type=search]').show();
});
$('#search-button').mouseleave(function () {
    $('[type=search]').hide();
});

$('.ui-menu-item').click(function(){
    
});

</script>
