<?php //var_dump ($this->getVars());  ?>
<div class="row">
    <div class="col-sm-6 col-xs-12">
    <!--<li>-->
    <div class="btn-section">
        
        <p>
            <a class="btn btn-<?= $this->row->color ?> btn-md" 
               href="<?= $this->url(array('section_id' => $this->row->id), 'note_note_index'); ?>" 
               role="button" title="Sekcja '<?= $this->row->fullname ?>'">
                <span class="pull-right">
                    <?= ($this->row->visibility == 0) ? '<i name="icon-changing-visibility" id="' . $this->row->id . '" class="fa fa-lock"></i>' : '<i name="icon-changing-visibility" id="' . $this->row->id . '" class="fa fa-globe"></i>' ?>
                </span>
                <?= $this->escape($this->row->fullname) ?>
            </a>
        </p>
    </div>
    </div>
    <!--</li>-->

    <!-- Domyślnie ukryte w main.js -->
    <div class="col-xs-6">
        <a href="<?= $this->url(array('section_id' => $this->row->id), 'note_section_edit'); ?>" name="edit-button" title="Edytuj sekcję..."><i class="fa fa-pencil fa-lg"></i></a>
        <a type="delete-action" href="<?= $this->url(array('section_id' => $this->row->id), 'note_section_delete'); ?>" name="delete-button" title="Czy na pewno chcesz kontynuować usuwanie rekordu? Usunięcie go może poskutować usunięciem elementów pokrewnych."><button class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button></a>
    </div>
</div>
<script>
(function() {
   
});
</script>