<?= $this->doctype(); // printing doctype ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl">
    <head>
        <?php $this->setPageTitle(); ?>
        <?php $this->setPageDescription(); ?>
        <?= $this->headTitle(); // printing page title ?>
        <?= $this->headMeta(); // printing description ?>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="robots" content="noindex">
        <!-- css style sheets -->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/bootstrap.css') ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/default.css') ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/jq-ui-autocomplete.css') ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/expanding-searchbox.css') ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/jquery.dataTables.css') ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/cover.css') ?>" />
        <!-- js scripts -->
        <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script src="<?php echo $this->baseUrl('js/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('js/bootbox.min.js'); ?>"></script>

        <script src="<?php echo $this->baseUrl('js/my.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('js/jquery.dataTables.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('js/dataTables.bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('js/expanding-searchbox.js'); ?>"></script>
        <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
        <script>
            tinymce.init({
                selector:'#tinymce',

                plugins: "textcolor", // ?
                menubar: false, // file, edit ....
                toolbar: "bold italic underline removeformat | styleselect | bullist numlist outdent indent | alignleft aligncenter alignright alignjustify | fontselect fontsizeselect  | subscript superscript  | hr link preview spellchecker"
            });
        </script>
        <link rel="icon" href="img/favicon.ico"/>
    </head>

    <body>
        <div class="site-wrapper">
            <div class="cover-container container-fluid">
                <div class="site-wrapper-inner">
                    
                    <header>
                        <div id="header"><?= $this->render('navbar.phtml') ?></div>
                    </header>
                    
                    <div class="space"></div>
                    
                    <main>
                        <?php  $this->getFlashMsg($this->msg) ?>
                        <?php echo $this->layout()->content //  layout() jest View Helperem ?> 
                    </main>
                    <footer>
                        <div id="mastfoot"><?= $this->render('mastfoot.phtml') ?></div>
                    </footer>
                    
                </div>
            </div>
        </div>
        
    </body>
    
</html>