<!-- Nie umieszczasz tutaj ".container-fluid", ponieważ cały navbar, content i mastfoot jest nim objęty :) -->

<div class="masthead clearfix">
    <div class="inner">
        <h3 class="masthead-brand">Witaj, 
            <?php if(isset($this->storage)) :  ?>
            <?= $this->storage[0]->user_username ?>
            <?php else : ?>
            gościu
            <?php endif ?>
        </h3>
        <nav>
            <ul class="nav masthead-nav">
                <li <?=isset($_SESSION['navbar']['home'])?'class="active"':'';?>><a href="<?= $this->url(array(), 'note_index_index') ?>">Home</a></li>
                <?php if(!isset($this->storage)) :  ?>
                    <li <?=isset($_SESSION['navbar']['zarejestruj'])?'class="active"':'';?>><a href="<?= $this->url(array(), 'note_auth_register') ?>">Zarejestruj</a></li>    
                    <li <?=isset($_SESSION['navbar']['zaloguj'])?'class="active"':'';?>><a href="<?= $this->url(array(), 'note_auth_login') ?>">Zaloguj</a></li>
                <?php else : ?>
                    <li><a href="<?= $this->url(array(), 'note_auth_logout') ?>">Wyloguj</a></li>
                <?php endif; ?>
                <li <?=isset($_SESSION['navbar']['przegladaj'])?'class="active"':'';?>><a href="<?= $this->url(array(),'note_section_index'); ?>">Przeglądaj</a></li>
            </ul>
        </nav>
    </div>
</div>

<!--    OSOBNY PANEL  *_ukryty_*   -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header navbar-left">
            <!--      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">A</span>
                    <span class="icon-bar">A</span>
                    <span class="icon-bar">A</span>
                  </button>-->
            <a class="navbar-brand" href="#">Panel logowania</a>
<!--            <a class="navbar-brand" href="#">Panel</a>-->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
<!--        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Profil <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Ustawienia</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>-->
            <!--      <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                  </form>-->

            <form class="form-inline navbar-right">
                <div class="form-group">
                    <label class="sr-only" for="exampleInputEmail3">Login</label>
                    <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Login">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="exampleInputPassword3">Hasło</label>
                    <input type="password" class="form-control" id="exampleInputPassword3" placeholder="Hasło">
                </div>
<!--                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Zapamiętaj
                    </label>
                </div>-->
                <button type="submit" class="btn btn-default">Zaloguj</button>
            </form>

            <!--      <ul class="nav navbar-nav navbar-right"> 
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                    </li>
                  </ul>-->
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<?php 
unset($_SESSION['navbar']);
?>