<div class="masthead clearfix">
    <div class="inner">
        <h4 class="masthead-brand">Witaj, 
            <?php if(isset($this->storage[0]->user_username)) :  ?>
            <?= $this->storage[0]->user_username ?>
            <?php else : ?>
            gościu
            <?php endif ?>
        </h4>
        <nav>
            <ul class="nav masthead-nav">
                <li <?=isset($_SESSION['navbar']['home'])?'class="active"':'';?>><a href="<?= $this->url(array(), 'note_index_index') ?>">Home</a></li>
                <?php if(!isset($this->storage)) :  ?>
                    <li <?=isset($_SESSION['navbar']['zarejestruj'])?'class="active"':'';?>><a href="<?= $this->url(array(), 'note_auth_register') ?>">Zarejestruj</a></li>    
                    <li <?=isset($_SESSION['navbar']['zaloguj'])?'class="active"':'';?>><a href="<?= $this->url(array(), 'note_auth_login') ?>">Zaloguj</a></li>
                <?php else : ?>
                    <li><a href="<?= $this->url(array(), 'note_auth_logout') ?>">Wyloguj</a></li>
                <?php endif; ?>
                <li <?=isset($_SESSION['navbar']['przegladaj'])?'class="active"':'';?>><a href="<?= $this->url(array(),'note_section_index'); ?>">Przeglądaj</a></li>
            </ul>
        </nav>
    </div>
</div>

<?php
unset($_SESSION['navbar']);